### ISSUE TITLE
[BUG] /servers Enpoint not working

### ISSUE THREAD

**Issue by kdev** [PhlexPlexico/G5API#119]
**Describe the bug**
Requesting the servers endpoint is always returning `{ servers: [] }` even when passing the authentication headers

**To Reproduce**
1. Send a request to `/servers` passing the headers

**Expected behavior**
It should return some server data

**Desktop (please complete the following information):**
 - OS: Windows
 - Node v16.6.2

**Server info**
 - OS: Ubuntu
 - Running in Docker

**Additional context**
This problem is due to how the super user status is currently checked ignoring any headers or body items
(See [here](https://github.com/PhlexPlexico/G5API/blob/master/routes/servers.js#L97)). 
_This could be fixed by just calling `Utils.ensureAuthenticated` and also checking for super admin there if no `req.user` is present_

**Comment by PhlexPlexico** [comment]
Does this log an error in the error logs then?

**Comment by kdev** [comment]
Checking for headers is probably a more elegant solution to this. Do you have the capacity to do this or should I take a look at it?

**Comment by PhlexPlexico** [comment]
PRs are always welcome! I'm kind of busy with some personal/work stuff for the next while here sadly.

**Comment by kdev** [comment]
Looking in to this there seems no way around looking up the super user/admin status in the DB. At least I don't see one.

**Comment by PhlexPlexico** [comment]
In the get call, you could simply check for header first, then get the user based on that. It's a bit of a big workaround for the one function though. For example:

```
check if header exists
query database with api/user id
if exists do admin checks based on result
else if header does not exist
fall back to regular user of req.user
```

I think that would make the most sense?

**Comment by kdev** [comment]
Since this is required by different paths in the _/servers_ endpoint writing a utility for this would be a good idea. I will try taking a look later today (it's 09:47 am) or next week!

**Comment by kdev** [comment]
Looking at the code I saw that you are using the `ensureAuthenticated` method here 
https://github.com/PhlexPlexico/G5API/blob/master/routes/servers.js#L251
I would like to use it as well

**Comment by PhlexPlexico** [comment]
The reasoning behind this is due to the fact that someone should know that servers do exist, however we should not allow them to view server specifics without being logged in (i.e. server IP and port).

**Comment by kdev** [comment]
Okay, but I don't see any reason why you should be able to see it. This would make sense for teams or matches but not really for servers.

**Comment by PhlexPlexico** [comment]
Hmm fair point. I suppose with getting the headers being checked as well this can probably be adjusted to add the `ensureAuthenticated` option. @thboss just be warned you'll need to add the API key and user id to the headers of Bot requests :)

Cheers!

**Comment by kdev** [comment]
> @thboss just be warned you'll need to add the API key and user id to the headers of Bot requests :)

Yep, this will probably break some things but shouldn't when you have send the API Key and user id as body params.

**Comment by PhlexPlexico** [comment]
Using the latest pull from master on the public panel it seems that I'm running into this issue with node 14.17.5:

```
/home/phlex/.pm2/logs/G5API-error-0.log last 15 lines:
0|G5API    | /home/phlex/G5API/utility/utils.js:133
0|G5API    |     const apiKey = req.get("user-api") || req.body[0]?.user_api;
0|G5API    | SyntaxError: Unexpected token '.'
0|G5API    |     at wrapSafe (internal/modules/cjs/loader.js:1067:16)
0|G5API    |     at Module._compile (internal/modules/cjs/loader.js:1115:27)
```

**Comment by PhlexPlexico** [comment]
Also do remember, if you choose to use /auth/steam and provide no login information whatsoever (i.e. fall through with no user), `ensureAuthenticated` will redirect you to the login. However that URL seems to not work as intended.

As an aside, it seems that this does not work with PM2 as well.

**Comment by kdev** [comment]
> 
> 
> Using the latest pull from master on the public panel it seems that I'm running into this issue with node 14.17.5:
> 
> ```
> /home/phlex/.pm2/logs/G5API-error-0.log last 15 lines:
> 0|G5API    | /home/phlex/G5API/utility/utils.js:133
> 0|G5API    |     const apiKey = req.get("user-api") || req.body[0]?.user_api;
> 0|G5API    | SyntaxError: Unexpected token '.'
> 0|G5API    |     at wrapSafe (internal/modules/cjs/loader.js:1067:16)
> 0|G5API    |     at Module._compile (internal/modules/cjs/loader.js:1115:27)
> ```

Looking into the `Dockerfile` I don't understand how this can work inside a Docker Container running node 13 as it looks like

**Comment by PhlexPlexico** [comment]
It's even using pm2 with node 15 I'm running into the same error:
```
--- PM2 report ----------------------------------------------------------------
Date                 : Wed Aug 25 2021 16:46:47 GMT+0000 (Coordinated Universal Time)
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 4.5.6
node version         : 15.8.0
node path            : /usr/bin/yarn
argv                 : /home/phlex/.nvm/versions/node/v15.8.0/bin/node,/home/phlex/G5API/node_modules/pm2/lib/Daemon.js
argv0                : /home/phlex/.nvm/versions/node/v15.8.0/bin/node
user                 : phlex
uid                  : 1000
gid                  : 1000
uptime               : 0min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 4.5.6
node version         : 15.8.0
node path            : /usr/bin/yarn
argv                 : /home/phlex/.nvm/versions/node/v15.8.0/bin/node,/home/phlex/G5API/node_modules/.bin/pm2,report
argv0                : /home/phlex/.nvm/versions/node/v15.8.0/bin/node
user                 : phlex
uid                  : 1000
gid                  : 1000
===============================================================================

```

**Comment by kdev** [comment]
using node 15 and still getting an error for `?.` does not make any sense because it's been [implemented in 14.0.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility)

**Comment by PhlexPlexico** [comment]
Okay not using the dockerfile I've seem to have everything sorted. But please note the last bit of that comment. The reason you're receiving no input is because you are probably being redirected. I just tried using the public panel with my API key and user id and I seem to be retrieving everything just fine
![image](https://user-images.githubusercontent.com/3514085/130832679-93762ca8-bef2-4261-a96c-aad8d9ddb42f.png)
