### ISSUE TITLE
[BUG] SQL Connections Failing Leading to Crash

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#54]
**Describe the bug**
Right now there seems to be an issue with the new transactions that were put into place. Once every so often an error will appear as the following and crash the app:

```
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]: /home/phlex/G5API/node_modules/mysql2/lib/pool.js:147
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]:       conn.query(cmdQuery).once('end', () => {
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]:                           ^
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]: TypeError: Cannot read property 'once' of undefined
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]:     at /home/phlex/G5API/node_modules/mysql2/lib/pool.js:147:27
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]:     at /home/phlex/G5API/node_modules/mysql2/lib/pool.js:44:37
Nov 03 07:58:48 phlex-ubuntu-vm startapi.sh[1421]:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

I'm not exactly sure what is causing it to crash, but if anyone has a solution I would be more than happy to resolve it.

**To Reproduce**
?

**Expected behavior**
Don't crash

**Screenshots**

**Desktop (please complete the following information):**

**Server info
 - OS: Ubuntu
 - Version 20.04
 - NodeJS version 13.13.0

**Additional context**

**Comment by PhlexPlexico** [comment]
I believe this was due to transactions and queries failing in various areas in the app. I think these should be fixed now and we do not go above 8 connections through testing.

**Comment by PhlexPlexico** [comment]
Reopening this as it seems to be happening again. I think it may have to do with the queries on the `GET`s so we may have to instantiate a single query for each time and close it after.

**Comment by PhlexPlexico** [comment]
This is currently running on the development instance now. Hopefully there can be some match creations and we can see if this crashes again.

**Comment by PhlexPlexico** [comment]
Another line on the Todo list as well is to swap to PM2, since if we do end up crashing it will just spin up another instance.
