### ISSUE TITLE
[BUG]  ifError got unwanted exception: Cannot find module 'async'

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#85]
**Describe the bug**

**To Reproduce**
Installation, run: yarn migrate-prod-upgrade

**Expected behavior**
DONE from the console

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 86

**Server info
 - OS: Debian
 - Version 10
 - NodeJS version v13.8.0

**Additional context**
Logs: 
`$ db-migrate --env production --config config/production.json up:production
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Cannot find module 'async'
Require stack:
- /var/www/g5/api/migrations/production/20191109191155-get5db.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/skeleton.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/migration.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/commands/helper/migration-hook.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/commands/up.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/commands/index.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/api.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/index.js
- /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/bin/db-migrate
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/www/g5/api/migrations/production/20191109191155-get5db.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Class.setup (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/skeleton.js:158:12)
    at /root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate/lib/migrator.js:231:41
    at tryCatcher (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/.nvm/versions/node/v13.8.0/lib/node_modules/db-migrate-mysql/node_modules/bluebird/js/release/async.js:15:14)`

**Comment by PhlexPlexico** [comment]
Did you do an initial `yarn install`?

**Comment by PhlexPlexico** [comment]
It also looks like you're trying to reference things globally? Yarn should just install into `/var/www/g5/api/node_modules` for you, and you shouldn't run into this problem.

**Comment by kubo6472** [comment]
Don't tell me I'm that dumb, nvm, I'm that dumb. Yea, thank you so much for your time and for bothering you with this stupid question. I tried installing the modules globally, locally, nuking the whole nodeJS with yarn and everything, but haven't found this way. This was my first time using yarn itself. Thanks again, hopefully, my last time asking dumb questions.

**Comment by PhlexPlexico** [comment]
Hey don't be sorry! Glad you were able to resolve it!! :) If you have any other issues feel free to open a new ticket!
